# Generated by Django 4.2.9 on 2024-02-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("phonenumber", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("ifLogged", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("username", models.CharField(max_length=255)),
                ("all_messages", models.CharField(max_length=25000)),
                (
                    "timestamp",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("Paytm", "Paytm"),
                            ("PhonePay", "PhonePay"),
                            ("Mic", "Mic"),
                            ("By Cash", "By Cash"),
                        ],
                        max_length=250,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("receiver", models.CharField(max_length=255)),
                ("receiver_category", models.CharField(max_length=255)),
                ("advice", models.CharField(max_length=1000)),
                ("t_type", models.CharField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("username", models.CharField(max_length=255)),
                (
                    "timestamp",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("img_file", models.FileField(upload_to="")),
                ("text", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
