# Generated by Django 4.2.9 on 2024-02-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_advice"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="user",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advice", name="advice", field=models.CharField(max_length=1000),
        ),
    ]
