# Generated by Django 4.2.9 on 2024-02-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_advice_user_alter_advice_advice"),
    ]

    operations = [
        migrations.RemoveField(model_name="advice", name="user",),
    ]
