from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app, resources={r"/api/*": {"origins": "http://localhost:3000"}})

@app.route('/api/level2-content')
def level2_content():
    content = "This is content generated by the Flask backend for Level 2."
    return jsonify({'content': content})

if __name__ == '__main__':
    app.run(debug=True, port=3000)
